//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPerInfo.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_MvcPersonelEntities : DbContext
    {
        public Db_MvcPersonelEntities()
            : base("name=Db_MvcPersonelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Gunler> Tbl_Gunler { get; set; }
        public virtual DbSet<Tbl_Kullanici> Tbl_Kullanici { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_CalismaTkvm> Tbl_CalismaTkvm { get; set; }
        public virtual DbSet<Tbl_MsjKad> Tbl_MsjKad { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Duyuru> Tbl_Duyuru { get; set; }
    }
}
