//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPerInfo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gunler
    {
        public byte ID { get; set; }
        public string GUNLER { get; set; }
        public string Vardiya { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string CalisanKisi { get; set; }
    }
}
