//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPerInfo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesajlar
    {
        public int MesajID { get; set; }
        public string Gonderen { get; set; }
        public string Alici { get; set; }
        public string GonderenMesaj { get; set; }
        public string AliciMesaj { get; set; }
    }
}
