//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPerInfo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CalismaTkvm
    {
        public int TakvimID { get; set; }
        public string UserKad { get; set; }
        public string CalismaGunu { get; set; }
        public string CalismaTarihi { get; set; }
        public string CaslimaVardiya { get; set; }
    }
}
