//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPerInfo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanici
    {
        public int ID { get; set; }
        public string KAD { get; set; }
        public string PASS { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string Email { get; set; }
        public string ResimYolu { get; set; }
        public string ResimAdi { get; set; }
        public string LoginDay { get; set; }
    }
}
